version: "2"
linters:
  # Default set of linters.
  # The value can be: `standard`, `all`, `none`, or `fast`.
  # Default: standard
  default: fast
  enable:
    - bodyclose
    - canonicalheader
    - contextcheck
    - funlen
    - nestif
    - cyclop
    - tagliatelle
    - tagalign
    - err113
    - errorlint
    - nilnil
    - nlreturn
    - noctx
    - rowserrcheck
    - whitespace
    - wsl
  disable:
    - wsl
    - gomodguard
    - mnd
    - prealloc
    - gocyclo
    - depguard
    - testpackage

  settings:
    funlen:
      # Checks the number of lines in a function.
      # If lower than 0, disable the check.
      # Default: 60
      lines: 120
      # Checks the number of statements in a function.
      # If lower than 0, disable the check.
      # Default: 40
      statements: 80
    nestif:
      min-complexity: 10
    cyclop:
      max-complexity: 15
    tagalign:
      align: true
      sort: false
      order:
        - json
        - form
        - mapstructure
        - yml
        - toml
        - mapstructure
        - binding
        - validate
        - example
    tagliatelle:
      case:
        rules:
          json: snake
          form: snake
          mapstructure: snake
          xml: snake
formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - goimports
    - golines
    - gofumpt

  settings:
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # The default order of sections is `standard > default > custom > blank > dot > alias > localmodule`,
      # If `custom-order` is `true`, it follows the order of `sections` option.
      # Default: ["standard", "default"]
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/org/) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        # Checks that no inline comments are present.
      # Default: false
      no-inline-comments: false
      # Checks that no prefix comments (comment lines above an import) are present.
      # Default: false
      no-prefix-comments: true
      # Enable custom order of sections.
      # If `true`, make the section order the same as the order of `sections`.
      # Default: false
      custom-order: true
      # Drops lexical ordering for custom sections.
      # Default: false
      no-lex-order: true