repos:
  # biome linter
  - repo: https://github.com/biomejs/pre-commit
    rev: v1.9.4
    hooks:
      - id: biome-check
        args:
          - src
  # vite build
  - repo: local
    hooks:
      - id: vite-build
        name: "Run Vite Build"
        entry: pnpm run build # 或者直接 'vite build' 如果已经全局安装了 vite
        language: system # 使用系统环境来执行命令
        types: [] # 这里可以为空，表示对所有文件都有效
  # png compress lossless
  - repo: https://github.com/shssoichiro/oxipng
    rev: v9.1.3
    hooks:
      - id: oxipng
        args: ["-o", "4", "--strip", "safe", "--alpha"]
  - repo: https://github.com/google/yamlfmt
    rev: v0.16.0
    hooks:
      - id: yamlfmt
        name: yamlfmt
        description: This hook uses github.com/google/yamlfmt to format yaml files. Requires Go >1.18 to be installed.
        entry: yamlfmt
        language: golang
        types: [yaml]
        args: ["-dstar", ".github/**/*.{yaml,yml}"]
        exclude: "pnpm-lock.yaml"
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args:
          - --verbose
          - --strict
          - comment
          - hotfix
          - build
          - chore
          - ci
          - docs
          - feat
          - fix
          - perf
          - refactor
          - revert
          - style
          - test
          - temp
          - update
