version: "3.8"
services:
  vite-react-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # 不要用 80:80 因为已经被占用了,最后 8000起
      - "8888:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
