/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OrderImport } from './routes/order'
import { Route as BotImport } from './routes/bot'

// Create/Update Routes

const OrderRoute = OrderImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRoute,
} as any)

const BotRoute = BotImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bot': {
      id: '/bot'
      path: '/bot'
      fullPath: '/bot'
      preLoaderRoute: typeof BotImport
      parentRoute: typeof rootRoute
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/bot': typeof BotRoute
  '/order': typeof OrderRoute
}

export interface FileRoutesByTo {
  '/bot': typeof BotRoute
  '/order': typeof OrderRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/bot': typeof BotRoute
  '/order': typeof OrderRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/bot' | '/order'
  fileRoutesByTo: FileRoutesByTo
  to: '/bot' | '/order'
  id: '__root__' | '/bot' | '/order'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  BotRoute: typeof BotRoute
  OrderRoute: typeof OrderRoute
}

const rootRouteChildren: RootRouteChildren = {
  BotRoute: BotRoute,
  OrderRoute: OrderRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/bot",
        "/order"
      ]
    },
    "/bot": {
      "filePath": "bot.jsx"
    },
    "/order": {
      "filePath": "order.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
